routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\OficinaController;
use App\Http\Controllers\RolController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('helpdesk');
});

//Auth::routes(['register' => false]);
Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::resource('tickets',TicketController::class);

Route::get('/helpdesk', [TicketController::class, 'index'])->name('helpdesk');

Route::get('/verificacion', [TicketController::class, 'passOfi'])->name('ticket.passOfi');

Route::post('/nuevoticket', [TicketController::class, 'store'])->name('ticket.store');

Route::get('/prueba', [TicketController::class, 'create'])->name('prueba');


Route::group(['middleware'=>['auth']],function(){
    Route::view('dashboard','dashboard')->name('dashboard');

    Route::get('/tickets/pendientes', [TicketController::class, 'ticketsPendientes'])->name('tickets.pendientes');

    Route::get('/tickets/solucionados', [TicketController::class, 'ticketsSolucionado'])->name('tickets.solucionados');

    Route::get('/tickets/cancelados', [TicketController::class, 'ticketsCancelado'])->name('tickets.cancelados');

    Route::get('/tickets/edit/{id}', [TicketController::class,'edit'])->name('tickets.edit');
    Route::put('/tickets/update/{ticket}', [TicketController::class,'update'])->name('tickets.update');
    Route::delete('/tickets/destroy/{id}', [TicketController::class,'destroy'])->name('tickets.destroy');

    Route::resource('usuarios',UsuarioController::class);
    Route::resource('oficinas', OficinaController::class)->names('oficinas');
    Route::resource('roles',RolController::class);
});

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $usuarios=User::all();
        return view('usuario.index',compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($user)
    {
        //
        $usuario=User::find($user);
        $roles=Role::get();
        //dd($usuario);
        return view('usuario.edit',compact('usuario','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $user)
    {
        //
        $usuario=User::find($user);
        //dd($request);
        $usuario->name=$request->input('nombre');
        $usuario->save();
        DB::table('model_has_roles')->Where('model_id',$user)->delete();

        $usuario->assignRole($request->input('rol'));

        return redirect()->route('usuarios.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/usuario/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <center>
        <h1>TICKETS</h1>
    </center>
@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 mt-4">
                <div class="card border-dark">
                    <h4 class="card-header border-dark bg bg-primary">EDITAR ROL</h4>
                    <div class="card-body">
                        {{--                        {!! Form::open(array('route'=>['teatro.update', $evento],'method'=>'POST','class'=>'mt-2')) !!}--}}
                        {{--                        @method('PUT')--}}
                        <form action="{{route('usuarios.update', $usuario)}}" method="POST">
                            @method('PUT')
                            @csrf
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label for="dni" class="form-label">
                                        Nombre:
                                        <span style="color: red;">*</span>
                                    </label>
                                    <input type="text" class="form-control" value="{{$usuario->name}}" name="nombre">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="celular" class="form-label">
                                        Email:
                                        <span style="color: red;">*</span></label>
                                    <input type="text" class="form-control" value="{{$usuario->email}}" name="email">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="estado" class="form-label">
                                        Rol:
                                        <span style="color: red;">*</span>
                                    </label>
                                    <select id="" class="form-control" name="rol">
                                    @foreach($roles as $rol)
                                        <option value="{{$rol->name}}">{{$rol->name}}</option>

                                    @endforeach
                                    </select>
                                </div>
                                {{--<div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <input type="checkbox" value="hola1"  name="permisos[]">
                                        </div>
                                    </div>
                                    <input type="text"  class="form-control" aria-label="Text input with checkbox" value="hola" disabled>

                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <input type="checkbox" value="hola2"  name="permisos[]">
                                        </div>
                                    </div>
                                    <input type="text"  class="form-control" aria-label="Text input with checkbox" value="hola" disabled>

                                </div>--}}
                                {{--<div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="">Permisos para este Rol:</label>
                                        <br/>
                                        @foreach($permisos as $permiso)
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text">
                                                        <input type="checkbox" value="{{$permiso->id}}" {{in_array($permiso->id, $rolePermissions)?'checked':''}}  name="permisos[]">
                                                    </div>
                                                </div>
                                                <input type="text"  class="form-control" aria-label="Text input with checkbox" value="{{$permiso->name}}" disabled>

                                            </div>--}}{{--
                                            <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}
                                                {{ $value->name }}</label>
                                            <br/>--}}{{--
                                        @endforeach
                                    </div>
                                </div>--}}

                                {{-- <div class="col-md-6 mb-3">
                                     <label for="celular" class="form-label">
                                         Celular:
                                         <span style="color: red;">*</span></label>
                                     <input type="text" class="form-control" value="{{$ticket->persona->celular}}" name="celular">
                                 </div>
                                 <div class="col-md-6 mb-3">
                                     <label for="incidencia" class="form-label">
                                         Incidencia:
                                         <span style="color: red;">*</span></label>
                                     <input type="text" class="form-control" value="{{$ticket->incidencia}}" name="incidencia">
                                 </div>
                                 <div class="col-md-6 mb-3">
                                     <label for="oficina" class="form-label">
                                         Oficina:
                                         <span style="color: red;">*</span>
                                     </label>
                                     <input type="text" class="form-control" value="{{$ticket->oficina->nombre_oficina}}" name="oficina">
                                 </div>
                                 <div class="col-md-6 mb-3">
                                     <label for="estado" class="form-label">
                                         Estado:
                                         <span style="color: red;">*</span>
                                     </label>
                                     <select id="" class="form-control" name="estado">
                                         <option value="Pendiente">Pendiente</option>
                                         <option value="Cancelado">Cancelado</option>
                                         <option value="Solucionado">Solucionado</option>
                                     </select>
                                 </div>--}}

                            </div>
                            <center>
                                <a href="../" class="btn btn-danger">Cancelar</a>
                                <button class="btn btn-primary">Confirmar</button>
                            </center>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@stop

@section('css')
@stop

@section('js')
    {{-- <script> console.log('Hi!'); </script> --}}
@stop

resources/views/usuario/index.blade.php
@extends('adminlte::page')

@section('title', 'Usuarios')

@section('content_header')
    <center>
        <h1>USUARIOS</h1>
    </center>
@stop

@section('content')
    <div class="table-responsive">
        <table id="pendientes" class="table table-striped mt-2">
            <thead>
            <th>NOMBRE</th>
            <th>EMAIL</th>
            <th>ROLES</th>
            <th>ACCIONES</th>
            </thead>
            <tbody>
            @foreach ($usuarios as $usuario)
                <tr class="">
                    <td>{{$usuario->name}}</td>
                    <td>{{$usuario->email}}</td>
                    <td>
                        @if(!empty($usuario->getRoleNames()))
                            @foreach($usuario->getRoleNames() as $rolName)
                                <h5><span class="badge bg-warning"> {{$rolName}} </span></h5></td>
                            @endforeach
                        @endif

                    <td>
                        <a href="{{route('usuarios.edit', $usuario->id)}}" class="btn btn-primary">Editar</a>
                        <form action="{{route('usuarios.destroy', $usuario->id)}}" method="post" style="display:inline">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-danger">Borrar</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@stop

@section('css')
@stop

@section('js')
    <script>
        $(document).ready(function () {
            $('#pendientes').DataTable();
        });
    </script>
@stop