routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\OficinaController;
use App\Http\Controllers\RolController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('helpdesk');
});

//Auth::routes(['register' => false]);
Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::resource('tickets',TicketController::class);

Route::get('/helpdesk', [TicketController::class, 'index'])->name('helpdesk');

Route::get('/verificacion', [TicketController::class, 'passOfi'])->name('ticket.passOfi');

Route::post('/nuevoticket', [TicketController::class, 'store'])->name('ticket.store');

Route::get('/prueba', [TicketController::class, 'create'])->name('prueba');


Route::group(['middleware'=>['auth']],function(){
    Route::view('dashboard','dashboard')->name('dashboard');

    Route::get('/tickets/pendientes', [TicketController::class, 'ticketsPendientes'])->name('tickets.pendientes');

    Route::get('/tickets/solucionados', [TicketController::class, 'ticketsSolucionado'])->name('tickets.solucionados');

    Route::get('/tickets/cancelados', [TicketController::class, 'ticketsCancelado'])->name('tickets.cancelados');

    Route::get('/tickets/edit/{id}', [TicketController::class,'edit'])->name('tickets.edit');
    Route::put('/tickets/update/{ticket}', [TicketController::class,'update'])->name('tickets.update');
    Route::delete('/tickets/destroy/{id}', [TicketController::class,'destroy'])->name('tickets.destroy');

    Route::resource('usuarios',UsuarioController::class);
    Route::resource('oficinas', OficinaController::class)->names('oficinas');
    Route::resource('roles',RolController::class);
});

app/Models/Oficina.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Oficina extends Model
{
    use HasFactory;
    public function tickets(){
        return $this->hasMany(Ticket::class);
    }
}

app/Http/Controllers/OficinaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Oficina;
use Illuminate\Http\Request;

class OficinaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $oficinas = Oficina::all();

        return view('oficinas.index', compact('oficinas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('oficinas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'oficina'=> 'required',
                'pass'=> 'required',
                'estado'=> 'required',
            ]
        );

        $input = $request->all();
        $nombre_ofi = $request->input('oficina');
        $pass = $request->input('pass');
        $estado = $request->input('estado');

        // dd($pass);

        $oficina = new Oficina;

        $oficina->nombre_oficina = $nombre_ofi;
        $oficina->estado = $estado;
        $oficina->password = $pass;


        $oficina->save();

        return redirect()->route('oficinas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Oficina  $oficina
     * @return \Illuminate\Http\Response
     */
    public function show(Oficina $oficina)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Oficina  $oficina
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $oficina = Oficina::find($id);
        // dd($evento);
        return view('oficinas.edit',compact('oficina'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Oficina  $oficina
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $evento = Oficina::find($id);

        $evento->nombre_oficina = $request->input('oficina');
        $evento->password = $request->input('pass');
        $evento->estado = $request->input('estado');
        // dd($evento);
        $evento->save();

        return redirect()->route('oficinas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Oficina  $oficina
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Oficina::find($id)->delete();
        return redirect()->route('oficinas.index');
    }
}

resources/views/oficinas/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<center>
    <h1>CREAR OFICINA</h1>
</center>
@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 mt-4">
                <div class="card border-dark">
                    <h4 class="card-header border-dark">NUEVA OFICINA</h4>
                    <div class="card-body">
                        {!! Form::open(array('route'=>'oficina.store','method'=>'POST','class'=>'mt-2')) !!}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="oficina" class="form-label">
                                    Nombre de la Oficina
                                <span style="color: red;">*</span>
                                </label>
                                {!! Form::text('oficina', null,array('class'=>'form-control '.($errors->has('oficina') ? 'is-invalid':''))) !!}
                                @error('oficina')
                            <span class="invalid-feedback">
                                <strong> {{$message}} </strong>
                            </span>
                            @enderror
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="pass" class="form-label">
                                    Contraseña:
                                    <span style="color: red;">*</span></label>
                                {!! Form::text('pass', null,array('class'=>'form-control '.($errors->has('pass') ? 'is-invalid':''))) !!}
                                @error('pass')
                            <span class="invalid-feedback">
                                <strong> {{$message}} </strong>
                            </span>
                            @enderror
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="estado" class="form-label">
                                    Estado:
                                <span style="color: red;">*</span>
                                </label>

                                {{Form::select('estado', ['0' => 'Activo', '1' => 'Inactivo'], null, ['class'=>'form-select']);}}
                            </div>
                        </div>
                        <center>
                            <button type="submit" class="btn btn-primary">Crear</button>
                            <a href="../oficina" class="btn btn-danger">Cancelar</a>
                        </center>
                        {!! Form::close() !!}
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    {{-- <script> console.log('Hi!'); </script> --}}
@stop

resources/views/oficinas/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<center>
    <h1>EDITAR OFICINA</h1>
</center>
@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 mt-4">
                <div class="card border-dark">
                    <h4 class="card-header border-dark">EDITAR RESERVA</h4>
                    <div class="card-body">
                        {{-- {!! Form::open(array('route'=>['oficina.update', $oficina],'method'=>'POST','class'=>'mt-2')) !!} --}}
                        <form action="{{route('oficinas.update', $oficina)}}" method="post">
                        @method('PUT')
                        @csrf

                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="oficina" class="form-label">
                                    Nombre de la Oficina
                                <span style="color: red;">*</span>
                                </label>
                                {{-- {!! Form::text('oficina',$oficina->nombre_oficina,array('class'=>'form-control '.($errors->has('oficina') ? 'is-invalid':''))) !!} --}}
                                <input type="text" value="{{$oficina->nombre_oficina}}" class="form-control" name="oficina">
                                @error('oficina')
                            <span class="invalid-feedback">
                                <strong> {{$message}} </strong>
                            </span>
                            @enderror
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="apellido_materno" class="form-label">
                                    Contraseña:
                                    <span style="color: red;">*</span></label>
                                {{-- {!! Form::text('pass',$oficina->password,array('class'=>'form-control '.($errors->has('fecha') ? 'is-invalid':''))) !!} --}}
                                <input type="text" value="{{$oficina->password}}" class="form-control" name="pass">
                                @error('fecha')
                            <span class="invalid-feedback">
                                <strong> {{$message}} </strong>
                            </span>
                            @enderror
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="estado" class="form-label">
                                    Estado:
                                <span style="color: red;">*</span>
                                </label>

                                {{-- {{Form::select('estado', ['0' => 'Activo', '1' => 'Inactivo'], $oficina->estado, ['class'=>'form-select']);}} --}}
                                <select name="estado" id="" class="form-control">
                                    @if ($oficina->estado == "0")
                                    <option value="0" selected>Activo</option>
                                    <option value="1" >Inactivo</option>
                                    @else
                                    <option value="0" >Activo</option>
                                    <option value="1" selected>Inactivo</option>
                                    @endif

                                </select>
                            </div>
                        </div>
                        <center>
                            <button href="" class="btn btn-primary">Confirmar</button>
                            <a href="../" class="btn btn-danger">Cancelar</a>
                        </center>
                        {{-- {!! Form::close() !!} --}}
                        </form>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    {{-- <script> console.log('Hi!'); </script> --}}
@stop

resources/views/oficinas/index.blade.php
@extends('adminlte::page')

@section('title', 'Oficinas')

@section('content_header')
<center>
    <h1>OFICINAS</h1>
</center>
@stop

@section('content')
    {{-- <a href=" {{ route('oficinas.create') }} " class="btn btn-success mb-3">NUEVA OFICINA</a> --}}
    <table id="oficinas" class="table table-striped mt-2">
        <thead>
            <th>NOMBRE DE OFICINA</th>
            <th>CONTRASEÑA</th>
            <th>ESTADO</th>
            <th>ACCIONES</th>
        </thead>
        <tbody>
            @foreach ($oficinas as $oficina)
            <tr class="">
                <td> {{$oficina->nombre_oficina}} </td>
                <td> {{$oficina->password}} </td>
                @if ($oficina->estado==="0")
                    <td><span class="badge bg-success" > Activo </span></td>
                @else
                    <td><span class="badge bg-warning" > Inactivo</span></td>
                @endif
                <td>
                    <a href=" {{ route('oficinas.edit', $oficina) }} " class="btn btn-primary">Editar</a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
@stop

@section('css')
    <link href="https://cdn.datatables.net/1.12.0/css/dataTables.bootstrap4.min.css" rel="stylesheet"></link>
@stop

@section('js')
    <script>
        $(document).ready(function () {
            $('#oficinas').DataTable();
        });
    </script>
@stop